### ISSUE TITLE
Define InvalidBackprop exception

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#100]
Currently `Tensor.backprop` and `Operation.backprop` raise a bare `Exception` for when raising for invalid backprop states. We should raise a more descriptive exceptions so that people don't have to do a bare try-except to catch these.

**Comment by Zac-HD** [comment]
Just a note - `except:` is equivalent to `except BaseException:`, not `except Exception:`; even though you almost always want the latter to avoid catching e.g. `KeyboardInterrupt`.
