### ISSUE TITLE
Implement weighted average

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#102]
See [numpy.average](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.average.html#numpy.average)

**Comment by bantmen** [comment]
Hey, I could take a stab at this if the issues are not stale. If all goes well, I could give https://github.com/rsokl/MyGrad/issues/117 a try too.

**Comment by rsokl** [comment]
Please do! That would be great. Let me know if you have any questions about the development process, including code / doc styles and testing.

#117 is a really neat one too - it will be more involved, but feel free to take a swing at it.

**Comment by bantmen** [comment]
Perfect. I'll put up a PR, then we can move on from there.

**Comment by bantmen** [comment]
Would it be possible to backprop over the weights?

**Comment by rsokl** [comment]
@bantmen sorry for missing this. I do think that we should permit backprop through the weights. Since they need not be normalized, it would be equivalent to backpropping through:

```python
(a * weights).sum(axis) / weights.sum(axis)
```

**Comment by bantmen** [comment]
@rsokl No problem! We can continue the discussion at the PR.

**Comment by rsokl** [comment]
Currently in progress at #215
