### ISSUE TITLE
Merge MyNN functionality into MyGrad

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#136]
I think it would make sense to merge mynn into mygrad. It would reduce significantly the overhead of maintaining the docs / test suite / packaging for two projects. Furthermore, it makes sense for mynn to be intimately-connected to mygrad on a versioning level.

@davidmascharka what are your thoughts? We could even strive to do:

```python
from mygrad import mynn
```

**Comment by davidmascharka** [comment]
Yeah I think from the beginning I wasn't sure it should exist as a separate project. Merging them makes a lot of sense, especially given the gradient weirdness and pain to track that down. Getting them more tightly integrated makes a lot of sense. Something like

``` python
from mygrad import mynn
```
or whatever seems pretty nice. It could probably (?) be absorbed into `mygrad.nnet` even. That seems like a pretty logical merge. I'll open a set of issues for completing this merge and link them across here and MyNN (hey this merge gets rid of our name issue :stuck_out_tongue:) so we can track this over the next couple days.

**Comment by rsokl** [comment]
Yeah I think it makes sense for it to just be in `mygrad.nnet`.

I would like to get mygrad to full coverage before we do the migration - it will help us track all of the newly-introduced code.

**Comment by davidmascharka** [comment]
That's definitely a good idea. I'll focus on code style management over there (black everything) and getting the test coverage improved on my end as well so we can merge things that have (ideally) full coverage and be pretty confident we're not breaking anything

**Comment by rsokl** [comment]
@davidmascharka there is now a `mygrad-2.0` branch that is configured to trigger Travis CI on all PRs. Thus you can start merging `mynn`, including API-breaking changes, to that branch

**Comment by rsokl** [comment]
I don't think we need this issue to remind ourselves of this..
