### ISSUE TITLE
Add tensor joining functions

### ISSUE THREAD

**Issue by meowklaski** [rsokl/MyGrad#16]
Write ops that mimic the behavior of:
- [x] [hstack](https://github.com/LLrsokl/MyGrad/projects/1)
- [x] [stack](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.stack.html#numpy.stack)
- [x] [vstack](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html#numpy.vstack)
- [x] [dstack](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.dstack.html#numpy.dstack)
- [x] [concatenate](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html#numpy.concatenate)
- [ ] [hsplit](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hsplit.html#numpy.hsplit)
- [ ] [block](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.block.html#numpy.block)

**Comment by Anonymission** [comment]
@rsokl 

I currently have ops, functions, and passing tests for concatenate, stack, d/h/vstack. I can make a PR if you haven't already started on your own versions.

**Comment by rsokl** [comment]
Yeah that would be great, please open a PR when you have a chance!

**Comment by rsokl** [comment]
See #62 for current state
