### ISSUE TITLE
numpy 1.17 update: empty_like et. al now accept a shape argument

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#174]
We should update `mygrad.empty_like`, `mygrad.ones_like`, `mygrad.zero_like`, and `mygrad.full_like` to accept a [`shape` argument](https://docs.scipy.org/doc/numpy/release.html#empty-like-and-related-functions-now-accept-a-shape-argument).

This does, however raise a question. How do we handle the numpy versioning issue. E.g. If someone passes the `shape` parameter, but has numpy 1.16.X installed, do we raise an error? Do we hack our implementation so that it will work rain or shine?

@Zac-HD do you have any insight into how you have handled this sort of thing?

**Comment by aslvrstn** [comment]
Given that this would only break people who update MyGrad, what do you think about just simultaneously bumping the min version of numpy to 1.17 in the PR that would make this change?

Or are you worried that there are people who can bump MyGrad but not numpy?

**Comment by Zac-HD** [comment]
I would either require Numpy >=1.17, or make it an error to pass the shape argument with earlier versions.

Terrible compat hacks have their place, but IMO only when you *know* that they let people use your library who otherwise wouldn't or couldn't.

**Comment by rsokl** [comment]
@aslvrstn, yes that is my concern. numpy is a limiting reagent for nearly all scientific computing packages in Python, and many packages are often slow to bump compatibility with newer versions of numpy.

I was thinking of writing a wrapper on these specific numpy functions - mirroring whatever interface numpy happens to expose - since they are so simple (they have no backprop capabilities). But ultimately I don't think that will work (without some pretty gross `functools` hacks), since I have to add a `constant` argument to the signature.

Ultimately, I probably will just raise if the user passes `shape` without the sufficient numpy version :/

**Comment by aslvrstn** [comment]
What do you mean by "slow to bump compatibility with newer versions of numpy"? All of this goes out the window if 1.17 is backwards incompatible, but unless another library explicitly has a _maximum_ version of numpy, everything should Just Work, no?

(To be clear, I don't have experience doing this. I could be missing a big part of how bumping the required version might break some other library's annoying stance.)

**Comment by rsokl** [comment]
NumPy 1.17 is now the minimum version supported by MyGrad 2.0
