### ISSUE TITLE
sum(tensor) vs tensor.sum() discrepancy

### ISSUE THREAD

**Issue by bantmen** [rsokl/MyGrad#209]
```
>>> sum(mg.Tensor(3))
0
>>> sum(mg.Tensor([3]))
Tensor(3)
>>> mg.Tensor(3).sum()
Tensor(3)
>>> mg.Tensor([3]).sum()
Tensor(3)
```

Is `sum(mg.Tensor(3))` returning 0 a bug or am I missing something?

FWIW, `mygrad.Tensor((3,)).sum()` returns 3.

**Comment by rsokl** [comment]
The issue is due to the fact that you are using the std-lib `sum` function. Rather, you should be using `mygrad.sum`

```python
>>> mg.sum(mg.Tensor(3))
Tensor(3)
```

**Comment by bantmen** [comment]
Got it. I assumed the two would behave the same because of the overloaded `__add__` method in tensor_base.py.

**Comment by rsokl** [comment]
Not quite since `mygrad.sum` actually implements a vectorized sum, whereas calling `sum` will just repeatedly call the `__add__` function between elements of an iterator. This is why `sum` was returning 0 in your example - it was being called on an empty iterator (a 0D tensor).

**Comment by bantmen** [comment]
Thanks for the explanation.
