### ISSUE TITLE
Add documentation about running tests locally

### ISSUE THREAD

**Issue by aslvrstn** [rsokl/MyGrad#211]
Right now the best way (I think!) to discover things is to read `.travis.yml` which isn't great.

I think just a line that says "Run `tox -e py37`" is sufficient to start. Though if there's a way of having it default to only a single environment that'd be great.

I can add this. Would you rather have it in the overall README or in a separate one?

**Comment by bantmen** [comment]
I use `pytest tests` - does that work for you too? For the developer setup, I've ran `python src/install.py developer`.

**Comment by rsokl** [comment]
@aslvrstn sorry I totally meant to respond earlier. I think including that tox command is a good call. And perhaps also a separate line "if you want to run this in your own environment run: pytest tests"

A PR is definitely welcome 😊

**Comment by aslvrstn** [comment]
https://github.com/rsokl/MyGrad/pull/212, but I don't think I have permission to link this issue in the PR
