### ISSUE TITLE
Add type-hints to MyGrad

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#30]
See the end of the thread 

~Provides type hint support without having to do heavy type annotations throughout the code.~

~### References~
~[mypy docs](https://github.com/python/mypy/wiki/Creating-Stubs-For-Python-Modules)~
~[stub file for numpy](https://github.com/machinalis/mypy-data/blob/master/numpy-mypy/numpy/__init__.pyi)~

**Comment by rsokl** [comment]
After talking to @Zac-HD I think the proper route is to simply introduce type-hints

**Comment by davidmascharka** [comment]
Is there a way to measure this and see what's not typed? Going to be adding typehints into `nnet` as features get pulled in but it would be great if we could do basically what codecov does and see what functions aren't typehinted.

**Comment by Zac-HD** [comment]
You can configure mypy to make un-annotated functions an error, globally or per-module.

**Comment by rsokl** [comment]
Closed by https://github.com/rsokl/MyGrad/pull/354

**Comment by rsokl** [comment]
(although the state of type annotations for MyGrad 2.0 is still very much a WIP. I don't have any static type checking instrumented in my CI)
