### ISSUE TITLE
Random sampling `mygrad.random`

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#43]
These no-backprop functions should simply wrap the corresponding numpy functions, but return tensors. `constant=False` should be included as a default argument. Simply write a wrapper that converts these numpy functions to mygrad ones (returning tensors). The return statement in the docstring should be updated as such. 

`mygrad/random/funcs.py`

- [ ] rand
- [ ] randn
- [ ] randint
- [ ] random_integers
- [ ] random_sample
- [ ] random
- [ ] ranf
- [ ] sample

**Comment by petarmhg** [comment]
Closed by #257.
