### ISSUE TITLE
logic routines

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#44]
The following no-backprop [numpy functions](https://docs.scipy.org/doc/numpy/reference/routines.logic.html) should be wrapped so that they can accept tensors *or* numpy arrays (or both). *These should all still return numpy arrays*.

`mygrad.logic`
- [x] logical_and  (via numpy override)
- [x] logical_or  (via numpy override)
- [x] logical_not  (via numpy override)
- [x] logical_xor  (via numpy override)
- [x] allclose  (via numpy override)
- [x] isclose
- [x] greater  (via numpy override)
- [x] greater_equal  (via numpy override)
- [x] less  (via numpy override)
- [x] less_equal  (via numpy override)
- [x] equal  (via numpy override)
- [x] not_equal

A wrapper might be useful here so that any tensors passed to the functions simply have their underlying numpy-arrays passed instead.

We ought not expose sophisticated arguments, like `out`, `casting`, `order`, `signature`, `subok`, or `extobj`

**Comment by HardBoiled800** [comment]
Is this issue still open? I see that David made a pull request, but I don't know if it addresses this issue or just the bitwise operators.

**Comment by davidmascharka** [comment]
That's just the bitwise operators. This is still open
