### ISSUE TITLE
Missing math functions

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#87]
The following math functions need implementations in `mygrad.math`. Please refer to the contents of that module for implementations of functions like `mygrad.exp` , `mygrad.sqrt`, `mygrad.arctan` for some guidance. 

- [exp2](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.exp2.html)
- [square](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.square.html)
- [arctan2](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arctan2.html)

**Comment by IanCoolidge0** [comment]
I'll pull request these three tonight. Is there any special optimization I should do for the square function or is it just there to mimic numpy?

**Comment by davidmascharka** [comment]
Addressed in #88
