### ISSUE TITLE
Can't set `constant`

### ISSUE THREAD

**Issue by davidmascharka** [rsokl/MyGrad#92]
I'd like to be able to set tensors to constant, but I cannot:

``` python
from mygrad import Tensor
weights = Tensor([1])
weights.constant = True

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-43-58d8e7751d9c> in <module>
----> 1 weights.constant = True

AttributeError: can't set attribute
```

A workaround is to set `weights._constant`; is this behavior intentional?

**Comment by rsokl** [comment]
I need to spend a little bit of time thinking about/testing a case where a tensor's `constant` gets toggled between operations in a common computational graph. I think it would behave properly already - as if we had a separate variable-tensor and constant-tensor being used in the graph.

**Comment by rsokl** [comment]
I think that the right answer here to permit people to set `constant` only if the tensor is not already participating in an operation as a non-constant.

**Comment by davidmascharka** [comment]
Would there be any problem if you involve the tensor in an operation, then set it to nonconstant?

``` python
c = a + b # with a constant
a.constant = False
c.mean().backward()
```

Here `a` shouldn't accumulate; would it?

**Comment by rsokl** [comment]
Yes, you're right about that. `a` should not accumulate a grad there. I think that this is easier than my past-self was saying. I should prioritize this.
