### ISSUE TITLE
Add mirrors to numpy objects like np.newaxis and np.float

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#96]
Create exact aliases for common numpy objects. E.g. ~`mygrad.newaxis`~ (this is done already) as a drop-in replacement for `np.newaxis`, `mygrad.float32` replaces `numpy.float32` etc. This is meant to allow people to search and replace `numpy` with `mygrad` and have their code still work.

TODO: make a list of all these objects

**Comment by petarmhg** [comment]
All [NumPy dtypes](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#built-in-scalar-types). Anything crossed out should not be mirrored, as `Tensor` only accepts numeric arrays. Other constants were added in PR #140 

- ~`bool_`~
- ~`bool8`~
- `byte`
- `short`
- `intc`
- `int_`
- `longlong`
- `intp`
- `int8`
- `int16`
- `int32`
- `int64`
- `ubyte`
- `ushort`
- `uintc`
- `uint`
- `ulonglong`
- `uintp`
- `uint8`
- `uint32`
- `uint64`
- `half`
- `single`
- `double`
- `float_`
- `longfloat`
- `float16`
- `float32`
- `float64`
- `float96`
- `float128`
- `csingle`
- `complex_`
- `clongfloat`
- `complex64`
- `complex128`
- `complex192`
- `complex256`
- ~`object_`~
- ~`bytes_`~
- ~`unicode_`~
- ~`void`~

**Comment by petarmhg** [comment]
Do we not want to support complex numbers in MyGrad? As of right now, it is valid to run:
```python
a = mg.Tensor([1, 2, 3])
b = mg.Tensor([1j, 2j, 3j])
c = a * b

c.backward()
```

where all gradients will be simply be complex valued:
```python
>>> a.grad
array([0.+1.j, 0.+2.j, 0.+3.j])
>>> b.grad
array([1.+0.j, 2.+0.j, 3.+0.j])
>>> c.grad
array([1.+0.j, 1.+0.j, 1.+0.j])
```

**Comment by rsokl** [comment]
I think you and I discussed this in person - we will not support complex numbers for now. It would require a substantial amount of work in the testing framework to exercise inputs on the complex plane (e.g. we wouldn't be able to use the complex-step method for numerical differentiation!)

**Comment by rsokl** [comment]
`mygrad.float32` is a thing now!
